version: '3'

services:
  prettydownloader:
    build: .
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      - DATA_DIR=/app/data
    volumes:
      - ./static:/app/static
      - ./data:/app/data
      - ./flask_session:/app/flask_session
    restart: unless-stopped
